"""Outbound dependencies required by authentication use cases."""
from datetime import datetime
from typing import Any, Protocol


class AuthRepositoryPort(Protocol):
    def find_user_by_email(self, email: str) -> dict[str, Any] | None: ...

    def create_user(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def store_refresh_token(self, jti: str, user_id: str, expires_at: datetime) -> None: ...

    def find_refresh_token(self, jti: str) -> dict[str, Any] | None: ...

    def revoke_refresh_token(self, jti: str) -> None: ...
