"""Outbound dependencies required by RAG use cases."""
from typing import Any, Protocol


class RagRepositoryPort(Protocol):
    def ensure_vector_index(self, dimensions: int) -> None: ...

    def store_chunks(self, book_id: str, chunks: list[dict[str, Any]]) -> None: ...

    def delete_chunks(self, book_id: str) -> None: ...

    def vector_search(self, query_vector: list[float], top_k: int) -> list[dict[str, Any]]: ...

    def get_indexed_book_ids(self) -> list[str]: ...
